### PR TITLE
Feat: re-translate for installation one of module

### PR DESCRIPTION
**Pull request by Rain120**
- [x] re-translate MobX and Decorators at installation

### CODE REVIEW

**Comment by Rain120** [comment]
@iChenLei 辛苦review一下

**Comment by iChenLei** [comment]
I am sorry for not reviewing this pull request.

**Review by iChenLei — APPROVED** [review]
LGTM

**Comment by Rain120** [comment]
> I am sorry for not reviewing this pull request.

It's ok, busy with work and life for anyone, cannot be fixed everything.

**Pull request merged**
